version: "3.9"

services:
  postgres_db:
    container_name: postgres
    build: ./database
    restart: always
    environment:
      - POSTGRES_USER=testEnvironment
      - POSTGRES_PASSWORD=testEnvironment
      - POSTGRES_DB=Vaccine
    ports:
      - "9500:5432"